chore: add required status checks

diff --git a/.github/workflows/codeql-analysis.yaml b/.github/workflows/codeql-analysis.yaml
--- a/.github/workflows/codeql-analysis.yaml
+++ b/.github/workflows/codeql-analysis.yaml
@@ -63,9 +63,7 @@ jobs:
       with:
         cache: maven
         distribution: temurin
-        java-version: |
-          11
-          25
+        java-version-file: .tool-versions
     - name: Initialize CodeQL
       uses: github/codeql-action/init@fdbfb4d2750291e159f0156def62b853c2798ca2 # v4.31.5
       with:
@@ -82,6 +80,15 @@ jobs:
     name: codeql-analysis.required-status-check
     needs:
     - analyze
+    # GitHub Actions skips this job when any of the dependents fail. And skips
+    # are considered success in their weird logic. So we always run it and fail
+    # ourselves if necessary
+    if: always()
     runs-on: ubuntu-latest
     steps:
     - run: echo "Use this job as the required status check of this workflow"
+    - name: Check that all jobs were successful
+      env:
+        RESULTS: ${{ toJSON(needs) }}
+      run: |
+        echo "$RESULTS" | jq -e 'all(.result == "success")' || exit 1
